[module]
[module.hugoVersion]
min = "0.80.0"
extended = true

[[module.imports]]
path = "github.com/danielfdickinson/metadata-image-mod-hugo-dfd"

[[module.imports]]
path = "github.com/danielfdickinson/link-handling-mod-hugo-dfd"
