[module]
  [module.hugoVersion]
    min = "0.80.0"
    extended = false

  [[module.imports]]
    path = "github.com/danielfdickinson/metadata-mod-hugo-dfd"

  [[module.imports]]
    path = "github.com/danielfdickinson/image-handling-mod-hugo-dfd"

  [[module.imports]]
    path = "github.com/danielfdickinson/link-handling-mod-hugo-dfd"
