name = "Dananke Hugo Theme"
homepage = "https://github.com/danielfdickinson/dananke-theme-hugo-dfd"
copyright = "© 2021-2022 Daniel F. Dickinson"
description = "Tweaked version of Ananke theme"

enableGitInfo = true
defaultContentLanguage = "en"

# See https://gohugo.io/content-management/multilingual/
# and https://www.regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/
[languages]
  [languages.en]
    languageName = "English"
    title = "Dananke Hugo theme"
    weight = 1

[author]
  name = "Daniel F. Dickinson"
  homepage = "https://www.wildtechgarden.ca/about/"
  copyright = "© 2021-2022 Daniel F. Dickinson"
  email = "dfdpublic@wildtechgarden.ca"

  [[author.authors]]
    name = "Daniel F. Dickinson"
    homepage = "https://www.wildtechgarden.ca/about/"
    copyright = "© 2021-2022 Daniel F. Dickinson"
    email = "dfdpublic@wildtechgarden.ca"

  [[author.authors]]
    name = "theNewDynamic"
    homepage = "https://www.thenewdynamic.com/"

[original]
  name = "theNewDynamic"
  homepage = "https://www.thenewdynamic.com/"

[module]
  [module.hugoVersion]
    min = "0.80.0"
    extended = false

  [[module.imports]]
    path = "github.com/danielfdickinson/metadata-mod-hugo-dfd"

  [[module.imports]]
    path = "github.com/danielfdickinson/image-handling-mod-hugo-dfd"

  [[module.imports]]
    path = "github.com/danielfdickinson/link-handling-mod-hugo-dfd"
