# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Dananke Hugo Theme"
license = "MIT"
licenselink = "https://github.com/danielfdickinson/dananke-theme-hugo-dfd/blob/master/LICENSE.md"
description = "Tweaked version of Ananke theme"
homepage = "https://github.com/danielfdickinson/dananke-theme-hugo-dfd"
tags = ["website", "starter", "responsive", "blog", "Tachyons", "Multilingual"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = "0.80.0"

[author]
name = "Daniel F. Dickinson"
homepage = "https://www.wildtechgarden.ca/about/"
copyright = "© 2021-2022 Daniel F. Dickinson"
email = "dfdpublic@wildtechgarden.ca"

[original]
name = "theNewDynamic"
homepage = "https://www.thenewdynamic.com/"