npx hyperlink public/index.html --canonicalroot https://example.com/ \
    --internal \
    --skip "https://www.facebook.com/sharer.php" \
    --skip "https://linkedin.com/shareArticle" \
    --skip "https://twitter.com/share" \
    --skip "https://www.pexels.com" \
    --skip "https://pixabay.com" \
    --skip "example.net" \
    --todo "301 http" \
    --todo "fragment-redirect" \
    -r -p public/index.html | tee check-links.log | npx tap-spot
