name: weekly-external-link-check
on:
  schedule:
    # At 2:20 AM -0500 on each Thursday strictly check all external links (301 Moved is a failure not just a warning)
    - cron: '20 7 * * 4'
jobs:
  build-unminified-site:
    runs-on: ubuntu-20.04
    steps:
      - name: "Build Site with Hugo and Audit"
        uses: danielfdickinson/build-audit-action-hugo-dfd@v0.2
        with:
          hugo-version: latest
          upload-site-as: unminified-site
          use-lfs: true
          source-directory: exampleSite
  check-external-links:
    needs: build-unminified-site
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Run Check external and internal links
        uses: danielfdickinson/link-check-action-hugo-dfd@v0.2
        with:
          canonical-root: https://example.com/
          check-external: true
          check-external-strict: true
          entry-point: index.html
          upload-logs-as: failing-weekly-external-check
          upload-logs-retention: 4
